# Generated by Django 4.2 on 2023-09-09 18:59

import csv_srv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csv_srv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="csv_data",
            field=models.FileField(
                default=csv_srv.models.default_csv, upload_to="csv_files/"
            ),
        ),
    ]
